# ---------- builder ----------
FROM node:20-alpine AS builder
WORKDIR /app

ENV NODE_ENV=development

COPY package.json ./

RUN npm install

COPY tsconfig.json ./
COPY src ./src

RUN npm run build

# ---------- runner ----------
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

COPY package.json ./
RUN npm install --omit=dev

COPY --from=builder /app/dist ./dist

CMD ["node", "dist/index.js"]
