export const waterEvents = [
  {
    id: 'event_moscow_river',
    title: 'Экскурсия по Москве-реке на теплоходе',
    category: 'water_tour',
    description: 'Прогулка по живописным местам Москвы-реки на комфортабельном теплоходе.',
    image: 'https://images.example.com/moscow-river.jpg',
    durationMinutes: 90,
    vesselType: 'teplohod',
    vesselId: 'vessel_moscow_81',
    seatMapId: 'seatmap_moscow_81',
    city: 'Москва',
    hasSeating: true,
    tags: ['вечерняя', 'экскурсия', 'река'],
    pierStart: 'Причал Киевский вокзал',
    pierEnd: 'Причал Киевский вокзал',
  },
  {
    id: 'event_neva_sunrise',
    title: 'Рассвет на Неве на скоростном катере',
    category: 'water_tour',
    description: 'Ранний утренний маршрут мимо главных достопримечательностей Петербурга.',
    image: 'https://images.example.com/neva-sunrise.jpg',
    durationMinutes: 70,
    vesselType: 'katamaran',
    vesselId: 'vessel_neva_sprint',
    seatMapId: 'seatmap_neva_sprint',
    city: 'Санкт-Петербург',
    hasSeating: true,
    tags: ['рассвет', 'река', 'скоростной катер'],
    pierStart: 'Университетская набережная, 17',
    pierEnd: 'Университетская набережная, 17',
  },
  {
    id: 'event_rent_yacht',
    title: 'Аренда яхты с капитаном',
    category: 'rental',
    description: 'Частная прогулка без фиксированных мест, гибкий маршрут и время.',
    image: 'https://images.example.com/yacht-rental.jpg',
    durationMinutes: 120,
    vesselType: 'yacht',
    vesselId: 'vessel_white_wave',
    seatMapId: null,
    city: 'Сочи',
    hasSeating: false,
    tags: ['приват', 'яхта', 'без мест'],
    pierStart: 'Сочи, Центральный причал',
    pierEnd: 'Сочи, Центральный причал',
  },
];

export const waterTrips = [
  {
    id: 'trip_moscow_evening',
    eventId: 'event_moscow_river',
    vesselId: 'vessel_moscow_81',
    date: '2025-07-15',
    time: '18:00',
    availableSeats: 124,
    basePrice: 1200,
    currency: 'RUB',
    pierStart: 'Причал Киевский вокзал',
    pierEnd: 'Причал Киевский вокзал',
  },
  {
    id: 'trip_moscow_late',
    eventId: 'event_moscow_river',
    vesselId: 'vessel_moscow_81',
    date: '2025-07-15',
    time: '21:00',
    availableSeats: 98,
    basePrice: 1400,
    currency: 'RUB',
    pierStart: 'Причал Киевский вокзал',
    pierEnd: 'Причал Киевский вокзал',
  },
  {
    id: 'trip_neva_sunrise',
    eventId: 'event_neva_sunrise',
    vesselId: 'vessel_neva_sprint',
    date: '2025-07-20',
    time: '05:30',
    availableSeats: 42,
    basePrice: 2200,
    currency: 'RUB',
    pierStart: 'Университетская набережная, 17',
    pierEnd: 'Университетская набережная, 17',
  },
  {
    id: 'trip_yacht_custom',
    eventId: 'event_rent_yacht',
    vesselId: 'vessel_white_wave',
    date: '2025-07-25',
    time: '12:00',
    availableSeats: 8,
    basePrice: 4500,
    currency: 'RUB',
    pierStart: 'Сочи, Центральный причал',
    pierEnd: 'Сочи, Центральный причал',
  },
];

export const waterSeatMaps = [
  {
    id: 'seatmap_moscow_81',
    name: 'Схема теплохода Москва-81',
    image: 'https://images.example.com/seatmap-moscow-81.png',
    vesselId: 'vessel_moscow_81',
    backgroundSvg: undefined,
    areas: [
      {
        id: 'deck_main',
        name: 'Главная палуба',
        category: 'standard',
        color: '#1f2937',
        price: 1500,
        seats: [
          { id: '1A', seatCode: '1A', alias: '1A', x: 120, y: 340, status: 'available', ticketsPerSeat: 1 },
          { id: '1B', seatCode: '1B', alias: '1B', x: 180, y: 340, status: 'available', ticketsPerSeat: 1 },
          { id: '2A', seatCode: '2A', alias: '2A', x: 120, y: 290, status: 'available', ticketsPerSeat: 1 },
          { id: '2B', seatCode: '2B', alias: '2B', x: 180, y: 290, status: 'available', ticketsPerSeat: 1 },
          { id: '3A', seatCode: '3A', alias: '3A', x: 120, y: 240, status: 'available', ticketsPerSeat: 1 },
          { id: '3B', seatCode: '3B', alias: '3B', x: 180, y: 240, status: 'available', ticketsPerSeat: 1 },
        ],
      },
      {
        id: 'deck_upper',
        name: 'Верхняя палуба',
        category: 'premium',
        color: '#0ea5e9',
        price: 2000,
        seats: [
          { id: 'U1', seatCode: 'U1', alias: 'U1', x: 220, y: 160, status: 'available', ticketsPerSeat: 1 },
          { id: 'U2', seatCode: 'U2', alias: 'U2', x: 260, y: 160, status: 'available', ticketsPerSeat: 1 },
          { id: 'U3', seatCode: 'U3', alias: 'U3', x: 300, y: 160, status: 'available', ticketsPerSeat: 1 },
        ],
      },
    ],
  },
  {
    id: 'seatmap_neva_sprint',
    name: 'Схема катамарана Sprint',
    image: 'https://images.example.com/seatmap-neva-sprint.png',
    vesselId: 'vessel_neva_sprint',
    backgroundSvg: undefined,
    areas: [
      {
        id: 'front_cabin',
        name: 'Передняя кабина',
        category: 'premium',
        color: '#0ea5e9',
        price: 2800,
        seats: [
          { id: 'F1', seatCode: 'F1', alias: 'F1', x: 120, y: 180, status: 'available', ticketsPerSeat: 1 },
          { id: 'F2', seatCode: 'F2', alias: 'F2', x: 170, y: 180, status: 'available', ticketsPerSeat: 1 },
          { id: 'F3', seatCode: 'F3', alias: 'F3', x: 220, y: 180, status: 'available', ticketsPerSeat: 1 },
          { id: 'F4', seatCode: 'F4', alias: 'F4', x: 270, y: 180, status: 'available', ticketsPerSeat: 1 },
        ],
      },
      {
        id: 'rear_cabin',
        name: 'Задняя кабина',
        category: 'standard',
        color: '#1f2937',
        price: 2400,
        seats: [
          { id: 'R1', seatCode: 'R1', alias: 'R1', x: 120, y: 260, status: 'available', ticketsPerSeat: 1 },
          { id: 'R2', seatCode: 'R2', alias: 'R2', x: 170, y: 260, status: 'available', ticketsPerSeat: 1 },
          { id: 'R3', seatCode: 'R3', alias: 'R3', x: 220, y: 260, status: 'available', ticketsPerSeat: 1 },
        ],
      },
    ],
  },
];

export const waterTicketTypes = [
  { id: 'adult', name: 'Взрослый', description: 'Полный билет для пассажиров от 12 лет' },
  { id: 'child', name: 'Детский', description: 'Детский билет от 5 до 12 лет' },
  { id: 'vip', name: 'VIP', description: 'Доступ в VIP-зону и приветственный напиток' },
];

export const waterSeatPrices = [
  { eventId: 'event_moscow_river', seatCategoryId: 'deck_main', ticketTypeId: 'adult', price: 1500, currency: 'RUB' },
  { eventId: 'event_moscow_river', seatCategoryId: 'deck_main', ticketTypeId: 'child', price: 1100, currency: 'RUB' },
  { eventId: 'event_moscow_river', seatCategoryId: 'deck_upper', ticketTypeId: 'adult', price: 2000, currency: 'RUB' },
  { eventId: 'event_moscow_river', seatCategoryId: 'deck_upper', ticketTypeId: 'vip', price: 2600, currency: 'RUB' },
  { eventId: 'event_neva_sunrise', seatCategoryId: 'front_cabin', ticketTypeId: 'adult', price: 2800, currency: 'RUB' },
  { eventId: 'event_neva_sunrise', seatCategoryId: 'front_cabin', ticketTypeId: 'child', price: 2200, currency: 'RUB' },
  { eventId: 'event_neva_sunrise', seatCategoryId: 'rear_cabin', ticketTypeId: 'adult', price: 2400, currency: 'RUB' },
];

export const waterVessels = [
  { id: 'vessel_moscow_81', name: 'Теплоход «Москва-81»', type: 'teplohod', deckCount: 2, seatMapId: 'seatmap_moscow_81' },
  { id: 'vessel_neva_sprint', name: 'Катамаран «Sprint»', type: 'katamaran', deckCount: 1, seatMapId: 'seatmap_neva_sprint' },
  { id: 'vessel_white_wave', name: 'Яхта «White Wave»', type: 'yacht', deckCount: 1, seatMapId: null },
];
